[package]
name = "llama-fidim"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "llama_fidim_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
fidim-core = { path = "../../crates/fidim-core" }
